### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by coderschoolreview** [triitvn/coderschool-tip-calculator#1]
Hi Tri Truong,

Thank you for your work hard, awesome !!!

Can you help me update your git image, the Video Walkthrough should be loaded when open README file.

An example of insert image to README file.
<img src='http://i.imgur.com/XPct148.gif' title='Your title' alt='Your alt content' />

CoderSchool.vn

**Comment by triitvn** [comment]
Hi @coderschoolreview I've already updated README.
